/**
 * @file main.c
 * @brief Hello World for QMTech SoC
 */

#include "soc_map.h"


// Definícia adresy displeja z tvojho project_config.yaml
#define SEG7_ADDR (*(volatile unsigned int*)0x80004000)

void delay(int cycles) {
    for (volatile int i = 0; i < cycles; i++);
}

void uart_putc(char c) {
    // Čakaj kým je TX FIFO plné (podľa status registra)
    while (!(UART0_STATUS & (1 << 1))); 
    UART0_DATA = c;
}

void uart_print(const char *str) {
    while (*str) uart_putc(*str++);
}

int main(void) {
    unsigned int counter = 0;

    // Pozdrav na úvod: "BEEF"
    SEG7_ADDR = 0xBEEF;
    delay(1000000);

    // Jednoduchá inicializácia
//    uart_print("QMTech RISC-V SoC Online!\r\n");
//    uart_print("Generated by Gemini Framework v1.0\r\n");

    while (1) {
        SEG7_ADDR = counter;
        counter++;
        if (counter > 0xFFFF) counter = 0;
        delay(200000); // Spomalenie, aby sme videli čísla bežať
        // Tu môže byť tvoja logika alebo obsluha VIC
    }

    return 0;
}
