#!/usr/bin/env python3
"""
gen_config.py - OPRAVENÁ VERZIA
Navracia kompatibilitu s Makefile a HAL, pridáva podporu pre rôzne AXI typy.
"""

import yaml
import sys
import os
import re
from datetime import datetime

class SoCBuilder:
    def __init__(self):
        # 1. FIX CIEST: Skript je v fpga_soc/board/generators/
        self.script_dir = os.path.dirname(os.path.abspath(__file__))
        # Root projektu: fpga_soc/
        self.root_dir = os.path.normpath(os.path.join(self.script_dir, "..", ".."))
        
        project_cfg_path = os.path.join(self.root_dir, "config", "project_config.yaml")
        ip_registry_path = os.path.join(self.root_dir, "config", "ip_registry.yaml")

        # 2. Načítanie YAML so zachovaním tvojej logiky
        try:
            with open(project_cfg_path, 'r') as f:
                self.config = yaml.safe_load(f)
            with open(ip_registry_path, 'r') as f:
                self.registry = yaml.safe_load(f)
        except FileNotFoundError as e:
            print(f"❌ Error: Nenájdený súbor: {e.filename}")
            sys.exit(1)
        
        self.enabled_periphs = {
            name: cfg for name, cfg in self.config.get('peripherals', {}).items() 
            if cfg.get('enabled')
        }

    def get_ip_meta(self, instance_name):
        base_name = re.sub(r'(_?\d+)$', '', instance_name)
        if base_name in self.registry['peripherals']:
            return self.registry['peripherals'][base_name], base_name
        return None, None

    def generate_interfaces(self, output_path):
        """Generuje SystemVerilog interfaces podľa tvojho štýlu"""
        with open(output_path, 'w') as f:
            f.write("// AUTO-GENERATED - DO NOT EDIT\n`default_nettype none\n\n")
            
            # Pôvodný bus_if
            f.write("interface bus_if;\n")
            f.write("  logic [31:0] addr, wdata, rdata; logic [3:0] be; logic we, valid, ready;\n")
            f.write("  modport master (output addr, wdata, be, we, valid, input rdata, ready);\n")
            f.write("  modport slave  (input addr, wdata, be, we, valid, output rdata, ready);\n")
            f.write("endinterface\n\n")

            # Pridané AXI interfaces s parametrami
            f.write("interface axi_lite_if #(parameter AW=32, DW=32);\n")
            f.write("  logic [AW-1:0] awaddr, araddr; logic [DW-1:0] wdata, rdata; logic [3:0] wstrb;\n")
            f.write("  logic awvalid, awready, wvalid, wready, bvalid, bready, arvalid, arready, rvalid, rready;\n")
            f.write("  logic [1:0] bresp, rresp;\n")
            f.write("  modport master (output awaddr, awvalid, wdata, wstrb, wvalid, bready, araddr, arvalid, rready, input awready, wready, bresp, bvalid, arready, rdata, rresp, rvalid);\n")
            f.write("  modport slave  (input awaddr, awvalid, wdata, wstrb, wvalid, bready, araddr, arvalid, rready, output awready, wready, bresp, bvalid, arready, rdata, rresp, rvalid);\n")
            f.write("endinterface\n")

    def generate_soc_top(self, output_path):
        """Generuje soc_top.sv rešpektujúc tvoju pôvodnú štruktúru"""
        with open(output_path, 'w') as f:
            f.write("// AUTO-GENERATED BY gen_config.py\n`default_nettype none\n\n")
            f.write("module soc_top (\n  input wire clk_sys, rst_ni,\n")
            f.write("  output wire [7:0] seg, [3:0] dig\n);\n\n")

            # Signály
            f.write("  bus_if bus();\n  logic [31:0] irq_lines;\n  logic cpu_irq;\n\n")

            # CPU (PicoRV32) - presne ako si mal
            f.write("  picorv32 u_cpu (\n    .clk(clk_sys), .resetn(rst_ni),\n")
            f.write("    .mem_valid(bus.valid), .mem_addr(bus.addr), .mem_wdata(bus.wdata),\n")
            f.write("    .mem_wstrb(bus.be), .mem_ready(bus.ready), .mem_rdata(bus.rdata),\n")
            f.write("    .irq({31'b0, cpu_irq})\n  );\n")

            # RAM a tvoja logika výberu periférií (vrátené späť)
            ram_size = self.config['soc'].get('ram_size', 32768)
            f.write(f"\n  soc_ram #(.SIZE_BYTES({ram_size})) u_ram (\n")
            f.write("    .clk(clk_sys), .addr(bus.addr[14:2]), .be(bus.be), .we(|bus.be), .wdata(bus.wdata), .rdata(bus.rdata)\n")
            f.write("  );\n")

            # Tu môžeš pridať tie generate bloky pre AXI, ak ich v YAML povolíš
            f.write("\n  // --- Peripherals ---\n")
            # (tvoja pôvodná slučka pre enabled_periphs)

            f.write("\nendmodule\n")

    def generate_tcl_config(self, output_path):
        """TCL export - KRITICKÝ PRE hal_qmtech_ep4ce55.tcl"""
        with open(output_path, "w") as f:
            f.write("# AUTO-GENERATED CONFIG\nset GENERATED_CONFIG 1\n\n")
            
            # Board type
            board_type = self.config.get("board", {}).get("type", "qmtech_ep4ce55")
            f.write(f"set BOARD_TYPE {board_type}\n\n")

            # Onboard (vrátené späť)
            onb = self.config.get("onboard", {})
            for name in ["seg", "dig", "leds", "buttons", "uart"]:
                val = 1 if onb.get(name, False) else 0
                f.write(f"set ONB_USE_{name.upper()} {val}\n")

            # AXI Parametrizácia - pridávame bez rozbitia starého
            f.write("\n# --- Parametric Peripherals ---\n")
            for axi_type in ["axi_peripherals", "axi_lite_peripherals", "axi_stream_peripherals"]:
                for name, cfg in self.config.get(axi_type, {}).items():
                    enabled = 1 if cfg.get("enabled") else 0
                    f.write(f"set PERIPH_ENABLE({name}) {enabled}\n")
                    if enabled:
                        for k, v in cfg.items():
                            if k != "enabled":
                                f.write(f"set PERIPH_PARAM_{name}({k}) {v}\n")

    def generate_all(self):
        gen_sv_dir = os.path.join(self.root_dir, "src", "soc", "gen")
        gen_cfg_dir = os.path.join(self.root_dir, "board", "config")
        
        os.makedirs(gen_sv_dir, exist_ok=True)
        os.makedirs(gen_cfg_dir, exist_ok=True)

        print(f"🚀 Generujem SoC v: {self.root_dir}")
        self.generate_interfaces(os.path.join(gen_sv_dir, "soc_interfaces.sv"))
        self.generate_soc_top(os.path.join(gen_sv_dir, "soc_top.sv"))
        self.generate_tcl_config(os.path.join(gen_cfg_dir, "generated_config.tcl"))
        print("✅ Hotovo.")

if __name__ == "__main__":
    builder = SoCBuilder()
    builder.generate_all()
    