# =============================================================================
# SCRIPT:  hal_qmtech_ep4ce55.tcl (Refactor 4.0)
# VERSION: 4.0 (Clean, Robust & Audit Ready)
#
# DESCRIPTION:
# Kompletná správa hardvéru pre QMTech Cyclone IV E:
# 1. Globálne nastavenia čipu a systémových pinov (CLK/RST)
# 2. On-board periférie (LED, SEG, DIG, UART, BUTTONS, VGA, SDRAM, ETH, SDC, CAM)
# 3. Dynamický PMOD Router pre J10 a J11
# 4. Generovanie synchronizačného súboru pre Audit (/out/macros_sync.tcl)
# =============================================================================

# -----------------------------------------------------------------------------
# 0. Helper Functions & Sync File Initialization
# -----------------------------------------------------------------------------

# Funkcia pre bezpečné priradenie v read-only móde počas auditu
proc safe_assign {cmd args} {
    if {[info exists ::IS_POST_FLOW_AUDIT] && $::IS_POST_FLOW_AUDIT} {
        return
    }
    eval $cmd $args
}

# Vytvorenie out adresára a otvorenie sync súboru
set SYNC_DIR  "out"
set SYNC_FILE "${SYNC_DIR}/macros_sync.tcl"
if {![file exists $SYNC_DIR]} { file mkdir $SYNC_DIR }

set m_fp [open $SYNC_FILE "w"]
puts $m_fp "# ============================================================================="
puts $m_fp "# GENERATED DOCUMENT: macros_sync.tcl"
puts $m_fp "# DATE: [clock format [clock seconds] -format {%Y-%m-%d %H:%M:%S}]"
puts $m_fp "# SOURCE: hal_qmtech_ep4ce55.tcl"
puts $m_fp "# DESCRIPTION: Autogenerated macro list for Hardware Audit synchronization."
puts $m_fp "# ============================================================================="
puts $m_fp "set ::ACTIVE_MACROS_LIST {}"

# -----------------------------------------------------------------------------
# 1. Global Device & System Constraints
# -----------------------------------------------------------------------------
safe_assign set_global_assignment -name FAMILY "Cyclone IV E"
safe_assign set_global_assignment -name DEVICE EP4CE55F23C8

# System clock
safe_assign set_location_assignment PIN_T2 -to SYS_CLK
safe_assign set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SYS_CLK

# Reset (Active Low)
safe_assign set_location_assignment PIN_W13 -to RESET_N
safe_assign set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to RESET_N
safe_assign set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to RESET_N

# -----------------------------------------------------------------------------
# 2. On-board Peripherals Mapping
# -----------------------------------------------------------------------------
set onb_map {
    SEG {C4 B2 A3 C3 A5 B4 B1 A4}
    DIG {B5 B3 B6}
    LEDS {E4 A8 B8 A7 B7 A6}
    BUTTONS {Y13 AA13}
    UART {J2 J1}
}

foreach peripheral [array names onb_map] {
    set var "ONB_USE_${peripheral}"
    if {[info exists $var] && [set $var]} {
        set pins $onb_map($peripheral)
        safe_assign set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to ONB_${peripheral}[*]
        if {$peripheral eq "BUTTONS"} {
            safe_assign set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to ONB_BUTTON[*]
        }
        set idx 0
        foreach pin $pins {
            safe_assign set_location_assignment $pin -to ONB_${peripheral}[$idx]
            incr idx
        }
    }
}

# -----------------------------------------------------------------------------
# 3. Dynamic PMOD Router & Macro Registration
# -----------------------------------------------------------------------------
array set PMOD_PIN_MAP {
    J10,1 "PIN_H1"  J10,2 "PIN_F1"  J10,3 "PIN_E1"  J10,4 "PIN_C1"
    J10,7 "PIN_H2"  J10,8 "PIN_F2"  J10,9 "PIN_D2"  J10,10 "PIN_C2"
    J11,1 "PIN_R1"  J11,2 "PIN_P1"  J11,3 "PIN_N1"  J11,4 "PIN_M1"
    J11,7 "PIN_R2"  J11,8 "PIN_P2"  J11,9 "PIN_N2"  J11,10 "PIN_M2"
}

proc assign_pmod_module {port module} {
    global PMOD_PIN_MAP
    set base "PMOD_${port}_P"

    if {[string match "HDMI*" $module] && $port ne "J11"} {
        return -code error "HW ERROR: HDMI vyzaduje J11 konektor."
    }

    # Default IO Standard
    set io_std "3.3-V LVTTL"
    if {[string match "HDMI*" $module]} { set io_std "LVDS" }

    safe_assign set_instance_assignment -name IO_STANDARD $io_std -to ${base}[*]

    # Pin order for module
    set pin_order {10 4 9 3 8 2 7 1}
    if {$module eq "SEG"} { set pin_order {10 9 3 4 8 2 1 7} }

    set idx 0
    foreach p_idx $pin_order {
        safe_assign set_location_assignment $PMOD_PIN_MAP($port,$p_idx) -to ${base}[$idx]
        incr idx
    }
}

# Apply PMOD configuration & register macros
foreach port [array names PMOD] {
    if {$PMOD($port) ne "NONE"} {
        assign_pmod_module $port $PMOD($port)
        set m_name1 "PMOD_${port}_IS_$PMOD($port)"
        set m_name2 "PMOD_${port}_ENABLED"

        set_global_assignment -name VERILOG_MACRO "${m_name1}=1"
        set_global_assignment -name VERILOG_MACRO "${m_name2}=1"

        puts $m_fp "lappend ::ACTIVE_MACROS_LIST {$m_name1}"
        puts $m_fp "lappend ::ACTIVE_MACROS_LIST {$m_name2}"
    }
}

# -----------------------------------------------------------------------------
# 4. On-board Macro Registration & Database Sync
# -----------------------------------------------------------------------------
set onb_list {LEDS SEG DIG BUTTONS UART VGA SDRAM ETH SDC CAM}
foreach p $onb_list {
    set var "ONB_USE_${p}"
    if {[info exists $var] && [set $var]} {
        set m_name "ONB_${p}_ENABLED"

        set_global_assignment -name VERILOG_MACRO "${m_name}=1"
        puts $m_fp "lappend ::ACTIVE_MACROS_LIST {$m_name}"
        post_message -type info "BSP: Peripheral ONB_${p} active. Macro registered."
    }
}

# -----------------------------------------------------------------------------
# 5. Close Sync File & Export Assignments
# -----------------------------------------------------------------------------
close $m_fp
if {[is_project_open] && (![info exists ::IS_POST_FLOW_AUDIT] || !$::IS_POST_FLOW_AUDIT)} {
    export_assignments
    post_message -type info "HAL: Assignments exported and sync file generated at $SYNC_FILE"
}
