"""
generators/rtl.py - RTL file generator (soc_top.sv, reg blocks, interfaces).
Uses Jinja2 templates.

v2 changes:
  - _render_soc: clock domain wire declarations
  - _render_soc: peripheral instantiation uses resolved clock_ports
    instead of hardcoded SYS_CLK
  - _render_soc: RAM clock resolved from clock_domain_map
  - _render_soc: CPU clock resolved from clock_domain_map
  - Consistent 2-space indentation throughout generated RTL
"""

from __future__ import annotations
import os, sys
from models import SoCModel, SoCMode, Peripheral, ResetSync
from generators.base import render, write


def _fail(msg):
    print(f"[ERROR] {msg}")
    sys.exit(1)


class RTLGenerator:

    def __init__(self, model: SoCModel):
        self.m = model

    def generate_interfaces(self, path: str) -> None:
        content = render("soc_interfaces.sv.j2")
        write(path, content)
        print("  -> soc_interfaces.sv")

    def generate_soc_top(self, path: str,
                          timing_cfg=None) -> None:
        m = self.m
        if m.mode == SoCMode.STANDALONE:
            content = self._render_standalone()
        else:
            content = self._render_soc(timing_cfg=timing_cfg)
        write(path, content)
        mode_str = "standalone" if m.mode == SoCMode.STANDALONE else "SoC mode"
        print(f"  -> soc_top.sv ({mode_str})")

    def generate_reg_block(self, p: Peripheral, path: str) -> None:
        module_name = f"{p.module}_regs"
        content = self._render_reg_block(p, module_name)
        write(path, content)
        print(f"  -> {os.path.basename(path)}")

    # =========================================================================
    # Register block
    # =========================================================================

    def _render_reg_block(self, p: Peripheral, module_name: str) -> str:
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        aw = p.addr_width
        # Use first clock port signal, fallback to SYS_CLK
        clk_sig = p.clock_ports[0].signal if p.clock_ports else "SYS_CLK"
        L = [
            "// AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY",
            f"// Generated: {ts}",
            f"// Register block for {p.module} @ 0x{p.base:08X}",
            f"// Instantiate as: {module_name} u_regs (.*);" ,
            "`default_nettype none",
            "",
            f"module {module_name} (",
            f"  input  wire        {clk_sig},",
            "  input  wire        RESET_N,",
            f"  input  wire [{aw+1}:2]  addr_i,",
            "  input  wire [31:0] wdata_i,",
            "  input  wire        we_i,",
            "  output logic [31:0] rdata_o",
        ]
        for r in p.registers:
            ws = f" [{r.width-1}:0]" if r.width > 1 else "      "
            L.append(f" ,output logic{ws} reg_{r.name.lower()}")
        L += [");", ""]

        for r in p.registers:
            ws = f" [{r.width-1}:0]" if r.width > 1 else "      "
            L.append(f"  logic{ws} r_{r.name.lower()}; "
                     f"// 0x{r.offset:02X}  {r.access.value}  {r.desc}")
        L.append("")

        writable = [r for r in p.registers if r.access.value in ("rw", "wo")]
        if writable:
            L += [
                f"  always_ff @(posedge {clk_sig} or negedge RESET_N) begin",
                "    if (!RESET_N) begin",
            ]
            for r in writable:
                L.append(f"      r_{r.name.lower()} <= {r.width}'h{r.reset:X};")
            L += ["    end else if (we_i) begin", f"      case (addr_i)"]
            for r in writable:
                L.append(
                    f"        {aw}'h{r.word_addr:X}: "
                    f"r_{r.name.lower()} <= wdata_i[{r.width-1}:0];")
            L += ["        default: ;", "      endcase", "    end", "  end", ""]

        L += ["  always_comb begin", "    rdata_o = 32'h0;", f"    case (addr_i)"]
        for r in p.registers:
            if r.access.value in ("rw", "ro"):
                L.append(
                    f"      {aw}'h{r.word_addr:X}: "
                    f"rdata_o = {{{{32-{r.width}{{1'b0}}}}, r_{r.name.lower()}}};")
        L += ["      default: rdata_o = 32'h0;", "    endcase", "  end", ""]

        for r in p.registers:
            L.append(f"  assign reg_{r.name.lower()} = r_{r.name.lower()};")

        L += ["", f"endmodule : {module_name}", "`default_nettype wire", ""]
        return "\n".join(L)

    # =========================================================================
    # Standalone top
    # =========================================================================

    def _render_standalone(self) -> str:
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        m = self.m
        lines = [
            "// AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY",
            f"// Generated: {ts}",
            "`default_nettype none",
            "",
            "module soc_top (",
            "  input  wire SYS_CLK,",
            "  input  wire RESET_N",
        ]
        for mod in m.standalone_modules:
            for ep in mod.ext_ports:
                ws = f" [{ep.width-1}:0]" if ep.width > 1 else "      "
                lines.append(f",")
                lines.append(f"  {ep.dir.sv()}{ws} {ep.top_port}")
        lines.append(");")
        lines.append("")
        for mod in m.standalone_modules:
            if mod.params:
                items = list(mod.params.items())
                lines.append(f"  {mod.module} #(")
                for i, (k, v) in enumerate(items):
                    sep = "" if i == len(items)-1 else ","
                    lines.append(f"    .{k}({v}){sep}")
                lines.append(f"  ) u_{mod.inst} (")
            else:
                lines.append(f"  {mod.module} u_{mod.inst} (")
            lines.append(f"    .{mod.clk_port} (SYS_CLK),")
            lines.append(f"    .{mod.rst_port} (RESET_N)")
            for ep in mod.ext_ports:
                lines.append(f"   ,.{ep.name} ({ep.top_port})")
            lines.append(f"  );")
            lines.append("")
        lines.append("endmodule : soc_top")
        return "\n".join(lines) + "\n"

    # =========================================================================
    # SoC top
    # =========================================================================

    def _render_soc(self, timing_cfg=None) -> str:
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        m = self.m
        # Build reset syncs if timing config provided
        self._build_reset_syncs(timing_cfg)
        L = []

        _latched   = "1" if m.ram_latency == "registered" else "0"
        _progaddr  = f"32'h{m.reset_vector:08X}"
        default_cpu = {
            "ENABLE_IRQ":        "1",
            "LATCHED_MEM_RDATA": _latched,
            "PROGADDR_RESET":    _progaddr,
        }
        cpu_params = {**default_cpu, **m.cpu_params}
        n = len(m.peripherals)

        # ------------------------------------------------------------------
        # Header + module port list
        # ------------------------------------------------------------------
        L += [
            "// AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY",
            f"// Generated: {ts}",
            "`default_nettype none",
            "",
            "module soc_top (",
            "  input  wire SYS_CLK,",
            "  input  wire RESET_N",
        ]
        for p in m.peripherals:
            for ep in p.ext_ports:
                ws = f" [{ep.width-1}:0]" if ep.width > 1 else "      "
                L.append(f",")
                L.append(f"  {ep.dir.sv()}{ws} {ep.top_port}")
        L += [");", ""]

        # ------------------------------------------------------------------
        # Clock domain wire declarations
        # ------------------------------------------------------------------
        # Collect all unique non-SYS_CLK signals used by any component
        clk_signals = set()
        for p in m.peripherals:
            for cp in p.clock_ports:
                if cp.signal != "SYS_CLK":
                    clk_signals.add(cp.signal)
        # RAM clock
        ram_clk_sig = self._resolve_ram_clock(m)
        if ram_clk_sig != "SYS_CLK":
            clk_signals.add(ram_clk_sig)
        # CPU clock
        cpu_clk_sig = self._resolve_cpu_clock(m)
        if cpu_clk_sig != "SYS_CLK":
            clk_signals.add(cpu_clk_sig)

        if clk_signals:
            L.append("  // ── Clock domain wires ──────────────────────────────────")
            for sig in sorted(clk_signals):
                # Reverse lookup: find domain name for comment
                domain = next(
                    (d for d, s in m.clock_domain_map.items() if s == sig),
                    sig)
                L.append(f"  // domain: {domain}")
                L.append(f"  wire {sig};")
                L.append(f"  // TODO: connect {sig} from PLL output port")
            L.append("")

        # ------------------------------------------------------------------
        # Reset synchroniser declarations and instantiations
        # ------------------------------------------------------------------
        if m.reset_syncs:
            L.append("  // ── Reset synchronisers ─────────────────────────────────")
            # Wire declarations
            for rs in m.reset_syncs:
                L.append(f"  wire {rs.rst_out};  "
                         f"// domain: {rs.domain}  type: {rs.sync_type}")
            L.append("")
            # Instances
            for rs in m.reset_syncs:
                L.append(f"  // {rs.inst_name}  ({rs.sync_type}"
                         + (f" from {rs.sync_from}" if rs.sync_from else "")
                         + ")")
                L.append(f"  cdc_reset_synchronizer #(.STAGES({rs.stages}))")
                L.append(f"  {rs.inst_name} (")
                L.append(f"    .clk_i  ({rs.clk_signal}),")
                L.append(f"    .rst_ni ({rs.rst_in}),")
                L.append(f"    .rst_no ({rs.rst_out})")
                L.append( "  );")
            L.append("")

        # ------------------------------------------------------------------
        # Bus, IRQ, selects
        # ------------------------------------------------------------------
        L += [
            "  // Bus and IRQ",
            "  bus_if       bus();",
            "  logic [31:0] irq_lines = '0;",
            "  logic        cpu_irq;",
            "",
            "  // Peripheral selects and read data",
            "  logic        ram_sel;",
        ]
        for p in m.peripherals:
            L.append(f"  logic        {p.inst}_sel;")
        L.append(f"  logic [31:0] periph_rdata [0:{n}];")
        L.append("")

        # ------------------------------------------------------------------
        # Address decoder
        # ------------------------------------------------------------------
        L += ["  // Address decoder", "  always_comb begin"]
        _rb = m.ram_base
        _rs = m.ram_size
        if m.ram_alias is not None:
            _ra = m.ram_alias
            L.append(
                f"    ram_sel = (bus.addr >= 32'h{_rb:08X} && "
                f"bus.addr < 32'h{_rb+_rs:08X}) ||")
            L.append(
                f"              (bus.addr >= 32'h{_ra:08X} && "
                f"bus.addr < 32'h{_ra+_rs:08X});")
        else:
            L.append(
                f"    ram_sel = (bus.addr >= 32'h{_rb:08X} && "
                f"bus.addr < 32'h{_rb+_rs:08X});")
        for p in m.peripherals:
            L.append(
                f"    {p.inst}_sel = "
                f"(bus.addr >= 32'h{p.base:08X}) && "
                f"(bus.addr < 32'h{p.base+p.size:08X});")
        L += ["  end", ""]

        # ------------------------------------------------------------------
        # RAM ready signal
        # ------------------------------------------------------------------
        if m.ram_latency == "registered":
            L += [
                "  // RAM read: 1-cycle registered ready (ram_latency=registered)",
                "  logic ram_sel_r;",
                f"  always_ff @(posedge {ram_clk_sig} or negedge RESET_N)",
                "    if (!RESET_N)        ram_sel_r <= 1'b0;",
                "    else if (ram_sel_r)  ram_sel_r <= 1'b0;",
                "    else                 ram_sel_r <= ram_sel & bus.valid;",
                "",
            ]
        else:
            L += [
                "  // RAM read: combinational ready (ram_latency=combinational)",
                "  logic ram_sel_r;",
                "  assign ram_sel_r = ram_sel & bus.valid;",
                "",
            ]

        # ------------------------------------------------------------------
        # Peripheral read pipeline
        # ------------------------------------------------------------------
        L += [
            "  // Peripheral read: registered select for LATCHED_MEM_RDATA=1",
            "  logic periph_sel_r;",
            "  logic [31:0] periph_rdata_r;",
            f"  always_ff @(posedge {cpu_clk_sig} or negedge RESET_N) begin",
            "    if (!RESET_N) begin",
            "      periph_sel_r   <= 1'b0;",
            "      periph_rdata_r <= 32'h0;",
            "    end else if (periph_sel_r) begin",
            "      periph_sel_r <= 1'b0;",
            "    end else begin",
            "      periph_sel_r <= bus.valid & ~ram_sel;",
        ]
        for idx, p in enumerate(m.peripherals, 1):
            L.append(
                f"      if ({p.inst}_sel & bus.valid) "
                f"periph_rdata_r <= periph_rdata[{idx}];")
        L += ["    end", "  end", ""]

        # ------------------------------------------------------------------
        # Read mux
        # ------------------------------------------------------------------
        L += [
            "  // Read data mux",
            "  always_comb begin",
            "    bus.rdata = '0;",
            "    bus.ready = 1'b0;",
            "    if (ram_sel_r) begin",
            "      bus.rdata = periph_rdata[0]; bus.ready = 1'b1;",
            "    end",
            "    else if (periph_sel_r) begin",
            "      bus.rdata = periph_rdata_r; bus.ready = 1'b1;",
            "    end",
            "  end",
            "",
        ]

        # ------------------------------------------------------------------
        # CPU instantiation
        # ------------------------------------------------------------------
        if m.cpu_type == "vexriscv":
            _clk_port = m.cpu_port_map.get("clk",   "SYS_CLK")
            _rst_port = m.cpu_port_map.get("rst_n",  "RESET_N")
            L += [
                f"  // VexRiscv CPU  reset_vector=0x{m.reset_vector:08X}"
                f"  clock={cpu_clk_sig}",
                "  vexriscv_wrapper u_cpu (",
                f"    .{_clk_port:<12} ({cpu_clk_sig}),",
                f"    .{_rst_port:<12} (RESET_N),",
                "    .bus_valid    (bus.valid),",
                "    .bus_addr     (bus.addr),",
                "    .bus_wdata    (bus.wdata),",
                "    .bus_be       (bus.be),",
                "    .bus_rdata    (bus.rdata),",
                "    .bus_ready    (bus.ready),",
                "    .timer_irq    (1'b0),",
                "    .external_irq (cpu_irq)",
                "  );",
                "",
            ]
        else:
            L.append(f"  // PicoRV32 CPU  clock={cpu_clk_sig}")
            L.append("  picorv32 #(")
            items = list(cpu_params.items())
            for i, (k, v) in enumerate(items):
                sep = "" if i == len(items)-1 else ","
                L.append(f"    .{k}({v}){sep}")
            L += [
                "  ) u_cpu (",
                f"    .clk       ({cpu_clk_sig}),",
                "    .resetn    (RESET_N),",
                "    .mem_valid (bus.valid),",
                "    .mem_addr  (bus.addr),",
                "    .mem_wdata (bus.wdata),",
                "    .mem_wstrb (bus.be),",
                "    .mem_ready (bus.ready),",
                "    .mem_rdata (bus.rdata),",
                "    .irq       ({31'b0, cpu_irq})",
                "  );",
                "",
            ]

        # ------------------------------------------------------------------
        # RAM instantiation
        # ------------------------------------------------------------------
        _pm    = m.ram_port_map
        _clk   = _pm.get("clk",   "clk")
        _addr  = _pm.get("addr",  "addr")
        _be    = _pm.get("be",    "be")
        _we    = _pm.get("we",    "we")
        _wdata = _pm.get("wdata", "wdata")
        _rdata = _pm.get("rdata", "rdata")
        _ram_rst = m.rst_signal_for_clock(ram_clk_sig)
        L += [
            f"  // On-chip RAM  {m.ram_size} B @ 0x{m.ram_base:08X}"
            f"  latency={m.ram_latency}  clock={ram_clk_sig}",
            f"  {m.ram_module} #(.SIZE_BYTES({m.ram_size}),"
            f" .INIT_FILE(\"{m.init_file}\"))",
            f"  {m.ram_inst} (",
            f"    .{_clk:<6} ({ram_clk_sig}),",
            f"    .{_addr:<6} (bus.addr[{m.ram_addr_top}:2]),",
            f"    .{_be:<6} (bus.be),",
            f"    .{_we:<6} (|bus.be & ram_sel & bus.valid),",
            f"    .{_wdata:<6} (bus.wdata),",
            f"    .{_rdata:<6} (periph_rdata[0])",
            "  );",
            "",
        ]

        # ------------------------------------------------------------------
        # Peripheral instantiations
        # ------------------------------------------------------------------
        L.append("  // Peripherals")
        for idx, p in enumerate(m.peripherals, 1):
            if p.params:
                L.append(f"  {p.module} #(")
                pitems = list(p.params.items())
                for i, (k, v) in enumerate(pitems):
                    sep = "" if i == len(pitems)-1 else ","
                    L.append(f"    .{k}({v}){sep}")
                L.append(f"  ) u_{p.inst} (")
            else:
                L.append(f"  {p.module} u_{p.inst} (")

            # Clock ports (one or more)
            for cp in p.clock_ports:
                L.append(f"    .{cp.port:<12} ({cp.signal}),")

            # Use resolved reset signal for this peripheral's clock domain
            _rst_sig = p.rst_signal if p.rst_signal else "RESET_N"
            L.append(f"    .{p.rst_port:<12} ({_rst_sig}),")
            L.append(f"    .addr_i       (bus.addr[{p.addr_width+1}:2]),")
            L.append(f"    .wdata_i      (bus.wdata),")
            L.append(f"    .we_i         (|bus.be & {p.inst}_sel & bus.valid),")
            L.append(f"    .rdata_o      (periph_rdata[{idx}])")
            for ep in p.ext_ports:
                L.append(f"   ,.{ep.name:<12} ({ep.top_port})")
            if len(p.irqs) == 1:
                L.append(f"   ,.irq_o        (irq_lines[{p.irqs[0].id}])")
            elif len(p.irqs) > 1:
                ids = ", ".join(
                    f"irq_lines[{irq.id}]" for irq in reversed(p.irqs))
                L.append(f"   ,.irq_o        ({{{ids}}})")
            L += ["  );", ""]

        L += ["  assign cpu_irq = |irq_lines;", "", "endmodule : soc_top", ""]
        return "\n".join(L)

    # =========================================================================
    # Helpers
    # =========================================================================

    def _build_reset_syncs(self, timing_cfg) -> None:
        """
        Builds ResetSync list from TimingConfig and stores in model.reset_syncs.
        Also:
          - resolves rst_signal for each peripheral based on its clock domain
          - adds cdc_reset_synchronizer files to model.extra_files
          - validates cdc_reset_synchronizer is in registry

        Called from _render_soc() when timing_cfg is provided.
        """
        from timing_loader import TimingConfig
        m = self.m
        if not timing_cfg or not isinstance(timing_cfg, TimingConfig):
            return

        # Check cdc_reset_synchronizer is available
        rst_sync_files = self._find_rst_sync_files()

        syncs = []
        # Map: domain -> rst_out wire name
        domain_rst_map: dict = {}

        # 1. Primary syncs (from clocks[].reset)
        for clk in timing_cfg.clocks:
            if not clk.reset:
                continue
            clk_signal = m.clock_domain_map.get(clk.name, clk.port)
            rst_out    = f"{clk.name.lower()}_rst_n"
            inst_name  = f"u_rst_sync_{clk.name.lower()}"
            syncs.append(ResetSync(
                inst_name  = inst_name,
                domain     = clk.name,
                clk_signal = clk_signal,
                rst_in     = clk.reset.port,
                rst_out    = rst_out,
                stages     = clk.reset.sync_stages,
                sync_type  = "primary",
                sync_from  = "",
            ))
            domain_rst_map[clk.name] = rst_out

        # 2. CDC syncs (from plls[].outputs[].reset.sync_from)
        for pll in timing_cfg.plls:
            for out in pll.outputs:
                if not out.reset or not out.reset.sync_from:
                    continue
                clk_signal = m.clock_domain_map.get(out.name, out.name)
                rst_in     = domain_rst_map.get(
                    out.reset.sync_from,
                    "RESET_N")   # fallback ak primary sync neexistuje
                rst_out    = f"{out.name.lower()}_rst_n"
                inst_name  = f"u_rst_sync_{out.name.lower()}"
                syncs.append(ResetSync(
                    inst_name  = inst_name,
                    domain     = out.name,
                    clk_signal = clk_signal,
                    rst_in     = rst_in,
                    rst_out    = rst_out,
                    stages     = out.reset.sync_stages,
                    sync_type  = "cdc",
                    sync_from  = out.reset.sync_from,
                ))
                domain_rst_map[out.name] = rst_out

        if not syncs:
            return

        m.reset_syncs = syncs

        # 3. Resolve rst_signal for each peripheral
        # domain_rst_map uses clock names from timing_cfg (e.g. "SYS_CLK", "pixel_clk")
        # peripheral clock_ports use logical domain names (e.g. "sys_clk", "pixel_clk")
        # Build signal->rst_out map for direct lookup
        signal_rst_map = {}
        for rs in syncs:
            signal_rst_map[rs.clk_signal] = rs.rst_out
            # Also map by domain name (for cases where domain == signal)
            signal_rst_map[rs.domain] = rs.rst_out

        for p in m.peripherals:
            if p.clock_ports:
                cp = p.clock_ports[0]
                # Try signal first, then domain name
                rst = signal_rst_map.get(cp.signal,
                      signal_rst_map.get(cp.domain, "RESET_N"))
            else:
                rst = "RESET_N"
            p.rst_signal = rst

        # 4. Add cdc_reset_synchronizer files to extra_files
        for f in rst_sync_files:
            if f not in m.extra_files:
                m.extra_files.append(f)

        n = len(syncs)
        domains = [rs.domain for rs in syncs]
        print(f"  [reset] {n} synchroniser(s): {', '.join(domains)}")

    def _find_rst_sync_files(self) -> list:
        """
        Find absolute paths for cdc_reset_synchronizer RTL files.
        Files are added to model.extra_files by gen_config.py._add_rst_sync_files().
        RTLGenerator itself does not have registry access -- returns empty here.
        gen_config.py calls _add_rst_sync_files AFTER generate_soc_top.
        """
        return []

    def _resolve_ram_clock(self, m: SoCModel) -> str:
        """Resolve physical clock signal for RAM from clock_domain_map."""
        domain = m.clock_domain_map.get("ram_clk",
                 m.clock_domain_map.get("sys_clk", "SYS_CLK"))
        # If value looks like a domain name (not a signal), resolve it
        if domain in m.clock_domain_map:
            return m.clock_domain_map[domain]
        return domain if domain else "SYS_CLK"

    def _resolve_cpu_clock(self, m: SoCModel) -> str:
        """Resolve physical clock signal for CPU from clock_domain_map."""
        domain = m.clock_domain_map.get("cpu_clk",
                 m.clock_domain_map.get("sys_clk", "SYS_CLK"))
        if domain in m.clock_domain_map:
            return m.clock_domain_map[domain]
        return domain if domain else "SYS_CLK"

    def verify_static_files(self, static_mods: list,
                            qsf_dir: str, root_dir: str) -> None:
        """Verify all static RTL files exist on disk."""
        for rel in static_mods:
            abs_path = os.path.normpath(os.path.join(qsf_dir, rel))
            if not os.path.exists(abs_path):
                _fail(
                    f"Missing RTL file: {abs_path}\n"
                    f"  Create {os.path.relpath(abs_path, root_dir)} "
                    f"or remove the peripheral from project_config.yaml."
                )
