"""
generators/rtl.py - RTL file generator (soc_top.sv, reg blocks, interfaces).
Uses Jinja2 templates.
"""

from __future__ import annotations
import os, sys
from models import SoCModel, SoCMode, Peripheral
from generators.base import render, write


def _fail(msg):
    print(f"[ERROR] {msg}")
    sys.exit(1)


class RTLGenerator:

    def __init__(self, model: SoCModel):
        self.m = model

    def generate_interfaces(self, path: str) -> None:
        content = render("soc_interfaces.sv.j2")
        write(path, content)
        print("  -> soc_interfaces.sv")

    def generate_soc_top(self, path: str) -> None:
        m = self.m
        if m.mode == SoCMode.STANDALONE:
            content = self._render_standalone()
        else:
            content = self._render_soc()
        write(path, content)
        mode_str = "standalone" if m.mode == SoCMode.STANDALONE else "SoC mode"
        print(f"  -> soc_top.sv ({mode_str})")

    def generate_reg_block(self, p: Peripheral, path: str) -> None:
        module_name = f"{p.module}_regs"
        content = self._render_reg_block(p, module_name)
        write(path, content)
        print(f"  -> {os.path.basename(path)}")

    def _render_reg_block(self, p: Peripheral, module_name: str) -> str:
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        aw = p.addr_width
        L = [
            "// AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY",
            f"// Generated: {ts}",
            f"// Register block for {p.module} @ 0x{p.base:08X}",
            f"// Instantiate as: {module_name} u_regs (.*);" ,
            "`default_nettype none",
            "",
            f"module {module_name} (",
            "  input  wire        SYS_CLK,",
            "  input  wire        RESET_N,",
            f"  input  wire [{aw+1}:2]  addr_i,",
            "  input  wire [31:0] wdata_i,",
            "  input  wire        we_i,",
            "  output logic [31:0] rdata_o",
        ]
        for r in p.registers:
            ws = f" [{r.width-1}:0]" if r.width > 1 else "      "
            L.append(f" ,output logic{ws} reg_{r.name.lower()}")
        L += [");", ""]

        for r in p.registers:
            ws = f" [{r.width-1}:0]" if r.width > 1 else "      "
            L.append(f"  logic{ws} r_{r.name.lower()}; // 0x{r.offset:02X}  {r.access.value}  {r.desc}")
        L.append("")

        writable = [r for r in p.registers if r.access.value in ("rw", "wo")]
        if writable:
            L += [
                "  always_ff @(posedge SYS_CLK or negedge RESET_N) begin",
                "    if (!RESET_N) begin",
            ]
            for r in writable:
                L.append(f"      r_{r.name.lower()} <= {r.width}'h{r.reset:X};")
            L += ["    end else if (we_i) begin", f"      case (addr_i)"]
            for r in writable:
                L.append(f"        {aw}'h{r.word_addr:X}: r_{r.name.lower()} <= wdata_i[{r.width-1}:0];")
            L += ["        default: ;", "      endcase", "    end", "  end", ""]

        L += ["  always_comb begin", "    rdata_o = 32'h0;", f"    case (addr_i)"]
        for r in p.registers:
            if r.access.value in ("rw", "ro"):
                L.append(f"      {aw}'h{r.word_addr:X}: rdata_o = {{{{32-{r.width}{{1'b0}}}}, r_{r.name.lower()}}};")
        L += ["      default: rdata_o = 32'h0;", "    endcase", "  end", ""]

        for r in p.registers:
            L.append(f"  assign reg_{r.name.lower()} = r_{r.name.lower()};")

        L += ["", f"endmodule : {module_name}", "`default_nettype wire", ""]
        return "\n".join(L)


    def _render_standalone(self) -> str:
        """Render standalone soc_top.sv using Python (not Jinja2) for formatting."""
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        m = self.m
        lines = []
        lines.append("// AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY")
        lines.append(f"// Generated: {ts}")
        lines.append("`default_nettype none")
        lines.append("")
        lines.append("module soc_top (")
        lines.append("  input  wire SYS_CLK,")
        lines.append("  input  wire RESET_N")
        for mod in m.standalone_modules:
            for ep in mod.ext_ports:
                ws = f" [{ep.width-1}:0]" if ep.width > 1 else "      "
                lines.append(f",")
                lines.append(f"  {ep.dir.sv()}{ws} {ep.top_port}")
        lines.append(");")
        lines.append("")
        for mod in m.standalone_modules:
            if mod.params:
                items = list(mod.params.items())
                lines.append(f"  {mod.module} #(")
                for i, (k, v) in enumerate(items):
                    sep = "" if i == len(items)-1 else ","
                    lines.append(f"    .{k}({v}){sep}")
                lines.append(f"  ) u_{mod.inst} (")
            else:
                lines.append(f"  {mod.module} u_{mod.inst} (")
            lines.append(f"    .{mod.clk_port} (SYS_CLK),")
            lines.append(f"    .{mod.rst_port} (RESET_N)")
            for ep in mod.ext_ports:
                lines.append(f"    ,.{ep.name} ({ep.top_port})")
            lines.append(f"  );")
            lines.append("")
        lines.append("endmodule : soc_top")
        return "\n".join(lines) + "\n"


    def _render_soc(self) -> str:
        """Render SoC soc_top.sv using Python for correct formatting."""
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        m = self.m
        L = []  # lines

        # LATCHED_MEM_RDATA must match ram_latency:
        #   registered    -> 1  (CPU waits one cycle, RAM registered output)
        #   combinational -> 0  (CPU expects data same cycle)
        _latched = "1" if m.ram_latency == "registered" else "0"
        _progaddr = f"32'h{m.reset_vector:08X}"
        default_cpu = {
            "ENABLE_IRQ":        "1",
            "LATCHED_MEM_RDATA": _latched,
            "PROGADDR_RESET":    _progaddr,
        }
        cpu_params = {**default_cpu, **m.cpu_params}
        n = len(m.peripherals)

        L += [
            "// AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY",
            f"// Generated: {ts}",
            "`default_nettype none",
            "",
            "module soc_top (",
            "  input  wire SYS_CLK,",
            "  input  wire RESET_N",
        ]
        for p in m.peripherals:
            for ep in p.ext_ports:
                ws = f" [{ep.width-1}:0]" if ep.width > 1 else "      "
                L.append(f",")
                L.append(f"  {ep.dir.sv()}{ws} {ep.top_port}")
        L += [");", ""]

        # Bus and IRQ
        L += [
            "  // Bus and IRQ",
            "  bus_if       bus();",
            "  logic [31:0] irq_lines = '0;",
            "  logic        cpu_irq;",
            "",
            "  // Peripheral selects and read data",
            "  logic        ram_sel;",
        ]
        for p in m.peripherals:
            L.append(f"  logic        {p.inst}_sel;")
        L.append(f"  logic [31:0] periph_rdata [0:{n}];")
        L.append("")

        # Address decoder
        L += ["  // Address decoder", "  always_comb begin"]
        # RAM decode: primary mapping at ram_base, optional alias
        _rb  = m.ram_base
        _rs  = m.ram_size
        if m.ram_alias is not None:
            _ra = m.ram_alias
            L.append(f"    ram_sel = (bus.addr >= 32'h{_rb:08X} && bus.addr < 32'h{_rb+_rs:08X}) ||")
            L.append(f"              (bus.addr >= 32'h{_ra:08X} && bus.addr < 32'h{_ra+_rs:08X});")
        else:
            L.append(f"    ram_sel = (bus.addr >= 32'h{_rb:08X} && bus.addr < 32'h{_rb+_rs:08X});")
        for p in m.peripherals:
            L.append(f"    {p.inst}_sel = "
                     f"(bus.addr >= 32'h{p.base:08X}) && "
                     f"(bus.addr < 32'h{p.base+p.size:08X});")
        L += ["  end", ""]

        # RAM ready
        L += [
        ]  # end of address decoder block

        # ── RAM ready signal: registered or combinational ──────────────────
        if m.ram_latency == "registered":
            L += [
                "  // RAM read: 1-cycle registered ready (ram_latency=registered)",
                "  logic ram_sel_r;",
                "  always_ff @(posedge SYS_CLK or negedge RESET_N)",
                "    if (!RESET_N)        ram_sel_r <= 1'b0;",
                "    else if (ram_sel_r)  ram_sel_r <= 1'b0;",
                "    else                 ram_sel_r <= ram_sel & bus.valid;",
                "",
            ]
        else:  # combinational
            L += [
                "  // RAM read: combinational ready (ram_latency=combinational)",
                "  logic ram_sel_r;",
                "  assign ram_sel_r = ram_sel & bus.valid;",
                "",
            ]

        # Registered periph select for LATCHED_MEM_RDATA=1
        L += [
            "  // Peripheral read: registered select for LATCHED_MEM_RDATA=1",
            "  logic periph_sel_r;",
            "  logic [31:0] periph_rdata_r;",
            "  always_ff @(posedge SYS_CLK or negedge RESET_N) begin",
            "    if (!RESET_N) begin",
            "      periph_sel_r   <= 1'b0;",
            "      periph_rdata_r <= 32'h0;",
            "    end else if (periph_sel_r) begin",
            "      periph_sel_r <= 1'b0;",
            "    end else begin",
            "      periph_sel_r <= bus.valid & ~ram_sel;",
        ]
        for idx, p in enumerate(m.peripherals, 1):
            L.append(f"      if ({p.inst}_sel & bus.valid) periph_rdata_r <= periph_rdata[{idx}];")
        L += ["    end", "  end", ""]

        # Read mux
        L += [
            "  // Read data mux",
            "  always_comb begin",
            "    bus.rdata = '0;",
            "    bus.ready = 1'b0;",
            "    if (ram_sel_r) begin",
            "      bus.rdata = periph_rdata[0]; bus.ready = 1'b1;",
            "    end",
            "    else if (periph_sel_r) begin",
            "      bus.rdata = periph_rdata_r; bus.ready = 1'b1;",
            "    end",
        ]
        L += ["  end", ""]

        # CPU instantiation - depends on cpu_type
        if m.cpu_type == 'vexriscv':
            # port_map from ip_registry.yaml via model.cpu_port_map
            _clk_port = m.cpu_port_map.get("clk",   "SYS_CLK")
            _rst_port = m.cpu_port_map.get("rst_n",  "RESET_N")
            L += [
                f"  // VexRiscv CPU (via wrapper)  reset_vector=0x{m.reset_vector:08X}",
                "  vexriscv_wrapper u_cpu (",
                f"    .{_clk_port:<12} (SYS_CLK),",
                f"    .{_rst_port:<12} (RESET_N),",
                "    .bus_valid    (bus.valid),",
                "    .bus_addr     (bus.addr),",
                "    .bus_wdata    (bus.wdata),",
                "    .bus_be       (bus.be),",
                "    .bus_rdata    (bus.rdata),",
                "    .bus_ready    (bus.ready),",
                "    .timer_irq    (1\'b0),",
                "    .external_irq (cpu_irq)",
                "  );",
                "",
            ]
        else:
            L.append("  // PicoRV32 CPU")
            L.append("  picorv32 #(")
            items = list(cpu_params.items())
            for i, (k, v) in enumerate(items):
                sep = "" if i == len(items)-1 else ","
                L.append(f"    .{k}({v}){sep}")
            L += [
                "  ) u_cpu (",
                "    .clk       (SYS_CLK),",
                "    .resetn    (RESET_N),",
                "    .mem_valid (bus.valid),",
                "    .mem_addr  (bus.addr),",
                "    .mem_wdata (bus.wdata),",
                "    .mem_wstrb (bus.be),",
                "    .mem_ready (bus.ready),",
                "    .mem_rdata (bus.rdata),",
                "    .irq       ({31\'b0, cpu_irq})",
                "  );",
                "",
            ]

        # RAM -- all names/ports driven by model (registry + project_config.yaml)
        _pm    = m.ram_port_map
        _clk   = _pm.get('clk',   'clk')
        _addr  = _pm.get('addr',  'addr')
        _be    = _pm.get('be',    'be')
        _we    = _pm.get('we',    'we')
        _wdata = _pm.get('wdata', 'wdata')
        _rdata = _pm.get('rdata', 'rdata')
        L += [
            f"  // On-chip RAM ({m.ram_size} bytes @ 0x{m.ram_base:08X}, latency={m.ram_latency})",
            f"  {m.ram_module} #(.SIZE_BYTES({m.ram_size}), .INIT_FILE(\"{m.init_file}\"))",
            f"  {m.ram_inst} (",
            f"    .{_clk:<6}(SYS_CLK),",
            f"    .{_addr:<6}(bus.addr[{m.ram_addr_top}:2]),",
            f"    .{_be:<6}(bus.be),",
            f"    .{_we:<6}(|bus.be & ram_sel & bus.valid),",
            f"    .{_wdata:<6}(bus.wdata),",
            f"    .{_rdata:<6}(periph_rdata[0])",
            "  );",
            "",
        ]

        # Peripherals
        L.append("  // Peripherals")
        for idx, p in enumerate(m.peripherals, 1):
            if p.params:
                L.append(f"  {p.module} #(")
                pitems = list(p.params.items())
                for i, (k, v) in enumerate(pitems):
                    sep = "" if i == len(pitems)-1 else ","
                    L.append(f"    .{k}({v}){sep}")
                L.append(f"  ) u_{p.inst} (")
            else:
                L.append(f"  {p.module} u_{p.inst} (")
            L.append(f"    .{p.clk_port} (SYS_CLK),")
            L.append(f"    .{p.rst_port} (RESET_N),")
            L.append(f"    .addr_i  (bus.addr[{p.addr_width+1}:2]),")
            L.append(f"    .wdata_i (bus.wdata),")
            L.append(f"    .we_i    (|bus.be & {p.inst}_sel & bus.valid),")
            L.append(f"    .rdata_o (periph_rdata[{idx}])")
            for ep in p.ext_ports:
                L.append(f"   ,.{ep.name} ({ep.top_port})")
            if len(p.irqs) == 1:
                L.append(f"   ,.irq_o (irq_lines[{p.irqs[0].id}])")
            elif len(p.irqs) > 1:
                ids = ", ".join(f"irq_lines[{irq.id}]" for irq in reversed(p.irqs))
                L.append(f"   ,.irq_o ({{{ids}}})")
            L += ["  );", ""]

        L += ["  assign cpu_irq = |irq_lines;", "", "endmodule : soc_top", ""]
        return "\n".join(L)

    def verify_static_files(self, static_mods: list, qsf_dir: str, root_dir: str) -> None:
        """Verify all static RTL files exist on disk."""
        for rel in static_mods:
            abs_path = os.path.normpath(os.path.join(qsf_dir, rel))
            if not os.path.exists(abs_path):
                _fail(
                    f"Missing RTL file: {abs_path}\n"
                    f"  Create {os.path.relpath(abs_path, root_dir)} "
                    f"or remove the peripheral from project_config.yaml."
                )
