"""
generators/sw.py - Software file generator (soc_map.h, soc_irq.h, sections.lds).
Uses Jinja2 templates.
"""

from __future__ import annotations
from models import SoCModel
from generators.base import render, write


class SWGenerator:

    def __init__(self, model: SoCModel):
        self.m = model

    def generate_soc_map_h(self, path: str) -> None:
        m = self.m
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "/* AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY */",
            f"/* Generated: {ts} */",
            "",
            "#ifndef SOC_MAP_H",
            "#define SOC_MAP_H",
            "",
            "#include <stdint.h>",
            "",
            f"#define SYS_CLK_HZ     {m.clock_freq}UL",
            f"#define RAM_SIZE_BYTES {m.ram_size}U",
        ]
        for p in m.peripherals:
            lines.append("")
            lines.append(f"/* {p.inst} @ 0x{p.base:08X}  ({p.module}) */")
            lines.append(f"#define {p.inst.upper()}_BASE (0x{p.base:08X}UL)")
            for r in p.registers:
                macro = f"#define {p.inst.upper()}_{r.name}_REG"
                val   = f"(*((volatile uint32_t*)({p.inst.upper()}_BASE + 0x{r.offset:02X}UL)))"
                comment = f"  /* {r.access.value}  {r.desc} */"
                lines.append(f"{macro} {val}{comment}")
        lines.extend(["", "#endif /* SOC_MAP_H */", ""])
        write(path, "\n".join(lines))
        print("  -> soc_map.h")

    def generate_soc_irq_h(self, path: str) -> None:
        m = self.m
        irqs = [
            (irq.id, f"{p.inst.upper()}_{irq.name.upper()}_IRQ")
            for p in m.peripherals
            for irq in p.irqs
        ]
        lines = []
        if irqs:
            for iid, iname in sorted(irqs):
                lines.append(f"#define {iname:<40s} {iid}U")
        else:
            lines.append("/* No interrupts configured */")

        content = (
            "/* AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY */\n\n"
            "#ifndef SOC_IRQ_H\n#define SOC_IRQ_H\n\n"
            + "\n".join(lines)
            + "\n\n#endif /* SOC_IRQ_H */\n"
        )
        write(path, content)
        print("  -> soc_irq.h")

    def generate_linker_script(self, path: str) -> None:
        content = render("sections.lds.j2", ram_size=self.m.ram_size)
        write(path, content)
        print("  -> sections.lds")

    def generate_ram_size_mk(self, path: str) -> None:
        """Generate ram_size.mk for sw/Makefile to include."""
        content = f"# AUTO-GENERATED - DO NOT EDIT\nRAM_SIZE = {self.m.ram_size}\n"
        write(path, content)
        print("  -> ram_size.mk")

    def generate_soc_map_md(self, path: str) -> None:
        m = self.m
        from datetime import datetime
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines = [
            "# SoC Memory Map\n",
            f"Generated: {ts}  |  Board: {m.board_type}  |  "
            f"Clock: {m.clock_freq//1_000_000} MHz  |  RAM: {m.ram_size} bytes\n\n",
            "## Address Space\n\n",
            "| Region | Base | End | Size | Module |\n",
            "|--------|------|-----|------|--------|\n",
            f"| RAM    | 0x00000000 | 0x{m.ram_size-1:08X} | {m.ram_size} B | soc_ram |\n",
        ]
        for p in m.peripherals:
            lines.append(
                f"| {p.inst} | 0x{p.base:08X} | 0x{p.end_addr:08X} "
                f"| 0x{p.size:X} | {p.module} |\n"
            )

        if any(p.registers for p in m.peripherals):
            lines.append("\n## Registers\n\n")
            for p in m.peripherals:
                if not p.registers:
                    continue
                lines.append(f"### {p.inst} (base: 0x{p.base:08X})\n\n")
                lines.append("| Offset | Name | Access | Width | Reset | Description |\n")
                lines.append("|--------|------|--------|-------|-------|-------------|\n")
                for r in p.registers:
                    macro = f"`{p.inst.upper()}_{r.name}_REG`"
                    lines.append(
                        f"| 0x{r.offset:02X} | {r.name} {macro} "
                        f"| {r.access.value} | {r.width} | 0x{r.reset:X} | {r.desc} |\n"
                    )
                lines.append("\n")

        irqs = [
            (irq.id, p.inst, irq.name)
            for p in m.peripherals for irq in p.irqs
        ]
        if irqs:
            lines.append("## Interrupts\n\n")
            lines.append("| ID | Peripheral | Name | C Macro |\n")
            lines.append("|----|-----------|------|--------|\n")
            for iid, inst, iname in sorted(irqs):
                macro = f"`{inst.upper()}_{iname.upper()}_IRQ`"
                lines.append(f"| {iid} | {inst} | {iname} | {macro} |\n")

        write(path, "".join(lines))
        print("  -> soc_map.md")
