board:
  type: qmtech_ep4ce55

paths:
  ip_plugins:
    - "cores"              # lokalny adresar vedla project_config.yaml
    - "../../../src/ip"

demo:
  name: blink_test_02
  mode: standalone

soc:
  clock_freq: 50000000

clock_domains:
  sys_clk:    SYS_CLK
  clk_100mhz: clk_100mhz

onboard:
  leds:    true
  seg:     false
  dig:     false
  buttons: false
  uart:    false

pmod:
  J10: LED
  J11: LED

standalone_modules:
  blink_01:
    module:  blink_test
    enabled: true
    params:
      CLK_FREQ: 100000000
    clock_domains:
      SYS_CLK: clk_100mhz
    port_overrides:
      ONB_LEDS: ONB_LEDS

  blink_02:
    module:  blink_test
    enabled: true
    params:
      CLK_FREQ: 100000000
    clock_domains:
      SYS_CLK: clk_100mhz
    port_overrides:
      ONB_LEDS: PMOD_J10_P

  blink_03:
    module:  blink_test
    enabled: true
    params:
      CLK_FREQ: 50000000
    port_overrides:
      ONB_LEDS: PMOD_J11_P

  pll:
    module:  ClkPll
    enabled: true
