board:
  type: qmtech_ep4ce55

paths:
  ip_plugins:
    - "../../../src/ip"

demo:
  name: blink_test
  mode: standalone

soc:
  clock_freq: 50000000

# Clock domain mapping: logical name -> physical signal
clock_domains:
  sys_clk:   SYS_CLK
  clk_100mhz: clk_100mhz

onboard:
  leds:    true
  seg:     false
  dig:     false
  buttons: false
  uart:    false

pmod:
  J10: NONE
  J11: NONE

standalone_modules:
  blink:
    module:  blink_test
    enabled: true
    params:
      CLK_FREQ: 100000000
    # blink_test bezi na 100 MHz domene
    clock_domains:
      SYS_CLK: clk_100mhz

  pll:
    module:  clkpll_inst
    enabled: true