# AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY
# Generated: 2026-03-22 15:31:22

set GENERATED_CONFIG 1
set BOARD_TYPE qmtech_ep4ce55

# --- On-board peripherals ---
set ONB_USE_SEG 1
set ONB_USE_DIG 1
set ONB_USE_LEDS 0
set ONB_USE_BUTTONS 1
set ONB_USE_UART 0
set ONB_USE_VGA 0
set ONB_USE_SDRAM 0
set ONB_USE_ETH 0
set ONB_USE_SDC 0
set ONB_USE_CAM 0

# --- PMOD configuration ---
set PMOD(J10) "NONE"
set PMOD(J11) "NONE"

# --- Active peripheral addresses ---
