#!/usr/bin/env python3
"""
gen_config.py — Kompletný SoC Orchestrátor (opravená a dokončená verzia)

Opravy:
  - Implementovaná periférna slučka v generate_soc_top()
  - Pridaná adresná kolízna kontrola
  - Pridané generovanie soc_map.h a soc_irq.h
  - Pridané generovanie sections.lds
  - Opravené cesty (skript je v board/generators/, root je o 2 úrovne vyššie)
  - Robustné načítanie ip_registry (všetko pod 'peripherals:')
"""

import yaml
import sys
import os
import re
from datetime import datetime


# =============================================================================
# Pomocné funkcie
# =============================================================================

AUTOGEN_HEADER = "// AUTO-GENERATED BY gen_config.py — DO NOT EDIT MANUALLY\n"
AUTOGEN_HEADER_TCL = "# AUTO-GENERATED BY gen_config.py — DO NOT EDIT MANUALLY\n"
AUTOGEN_HEADER_C   = "/* AUTO-GENERATED BY gen_config.py — DO NOT EDIT MANUALLY */\n"


def ts():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


# =============================================================================
# SoCBuilder
# =============================================================================

class SoCBuilder:

    def __init__(self):
        # Skript je v: <root>/board/generators/gen_config.py
        self.script_dir = os.path.dirname(os.path.abspath(__file__))
        self.root_dir   = os.path.normpath(os.path.join(self.script_dir, "..", ".."))

        cfg_dir = os.path.join(self.root_dir, "board", "config")
        project_cfg_path = os.path.join(cfg_dir, "project_config.yaml")
        ip_registry_path = os.path.join(cfg_dir, "ip_registry.yaml")

        try:
            with open(project_cfg_path, 'r') as f:
                self.config = yaml.safe_load(f)
            with open(ip_registry_path, 'r') as f:
                self.registry = yaml.safe_load(f)
        except FileNotFoundError as e:
            print(f"❌  Chyba: Nenájdený súbor: {e.filename}")
            sys.exit(1)
        except yaml.YAMLError as e:
            print(f"❌  Chyba v YAML súbore: {e}")
            sys.exit(1)

        # Aktívne periférie z project_config
        self.enabled_periphs = {
            name: cfg
            for name, cfg in self.config.get('peripherals', {}).items()
            if isinstance(cfg, dict) and cfg.get('enabled')
        }

        # Validácia adresných kolízií — kritická kontrola pred generovaním
        self._check_address_collisions()

    # -------------------------------------------------------------------------
    # Pomocné metódy
    # -------------------------------------------------------------------------

    def get_ip_meta(self, instance_name):
        """
        Vráti metadata z ip_registry pre daný názov inštancie.
        Ak sa nenájde priama zhoda, skúsi odstrániť číselný suffix (uart0 → uart).
        """
        reg_periphs = self.registry.get('peripherals', {})
        if instance_name in reg_periphs:
            return reg_periphs[instance_name], instance_name

        # Skúsiť bez suffixu
        base_name = re.sub(r'_?\d+$', '', instance_name)
        # Skúsiť aj podľa 'type' kľúča v project_config
        periph_cfg = self.config.get('peripherals', {}).get(instance_name, {})
        type_name  = periph_cfg.get('type', base_name)

        for candidate in [base_name, type_name]:
            if candidate in reg_periphs:
                return reg_periphs[candidate], candidate

        return None, None

    def _check_address_collisions(self):
        """Kontrola, či dve periférie nezdieľajú adresný priestor."""
        ranges = []
        for name, cfg in self.enabled_periphs.items():
            base = cfg.get('base')
            if base is None:
                continue
            meta, _ = self.get_ip_meta(name)
            size = meta.get('address_range', 0x10) if meta else 0x10
            # Konverzia na int ak je string (napr. "0x10")
            if isinstance(size, str):
                size = int(size, 16)
            end = base + size - 1
            for other_name, other_base, other_end in ranges:
                if base <= other_end and end >= other_base:
                    print(f"❌  Adresná kolízia: '{name}' (0x{base:08X}..0x{end:08X})"
                          f" prekrýva '{other_name}' (0x{other_base:08X}..0x{other_end:08X})")
                    sys.exit(1)
            ranges.append((name, base, end))
        print(f"✅  Adresná mapa: {len(ranges)} periférií, žiadne kolízie.")

    def _get_external_ports(self):
        """
        Zozbiera všetky externé porty (signály smerujúce von z čipu)
        z aktívnych periférií podľa ip_registry.
        Vracia list: (periph_instance, signal_name, dir, width)
        """
        ports = []
        for name in self.enabled_periphs:
            meta, _ = self.get_ip_meta(name)
            if not meta:
                continue
            for iface in meta.get('interfaces', []):
                if iface.get('type') in ('serial', 'display', 'gpio', 'video',
                                          'memory', 'interface'):
                    for sig in iface.get('signals', []):
                        ports.append({
                            'periph': name,
                            'name':   sig['name'],
                            'dir':    sig['dir'],
                            'width':  sig.get('width', 1),
                        })
        return ports

    # -------------------------------------------------------------------------
    # Generator: soc_interfaces.sv
    # -------------------------------------------------------------------------

    def generate_interfaces(self, output_path):
        with open(output_path, 'w') as f:
            f.write(AUTOGEN_HEADER)
            f.write(f"// Generated: {ts()}\n")
            f.write("`default_nettype none\n\n")

            # Simple bus (pre PicoRV32 natívne mem rozhranie)
            f.write("// --- Simple memory-mapped bus ---\n")
            f.write("interface bus_if;\n")
            f.write("  logic [31:0] addr;\n")
            f.write("  logic [31:0] wdata;\n")
            f.write("  logic [31:0] rdata;\n")
            f.write("  logic [3:0]  be;\n")
            f.write("  logic        we;\n")
            f.write("  logic        valid;\n")
            f.write("  logic        ready;\n")
            f.write("  modport master (output addr, wdata, be, we, valid,\n"
                    "                  input  rdata, ready);\n")
            f.write("  modport slave  (input  addr, wdata, be, we, valid,\n"
                    "                  output rdata, ready);\n")
            f.write("endinterface : bus_if\n\n")

            # AXI-Lite
            f.write("// --- AXI4-Lite ---\n")
            f.write("interface axi_lite_if #(\n"
                    "  parameter int AW = 32,\n"
                    "  parameter int DW = 32\n"
                    ");\n")
            f.write("  logic [AW-1:0] awaddr, araddr;\n"
                    "  logic [DW-1:0] wdata, rdata;\n"
                    "  logic [3:0]    wstrb;\n"
                    "  logic          awvalid, awready;\n"
                    "  logic          wvalid,  wready;\n"
                    "  logic          bvalid,  bready;\n"
                    "  logic [1:0]    bresp;\n"
                    "  logic          arvalid, arready;\n"
                    "  logic          rvalid,  rready;\n"
                    "  logic [1:0]    rresp;\n\n")
            f.write("  modport master (\n"
                    "    output awaddr, awvalid, wdata, wstrb, wvalid, bready,\n"
                    "           araddr, arvalid, rready,\n"
                    "    input  awready, wready, bresp, bvalid, arready,\n"
                    "           rdata, rresp, rvalid\n"
                    "  );\n"
                    "  modport slave (\n"
                    "    input  awaddr, awvalid, wdata, wstrb, wvalid, bready,\n"
                    "           araddr, arvalid, rready,\n"
                    "    output awready, wready, bresp, bvalid, arready,\n"
                    "           rdata, rresp, rvalid\n"
                    "  );\n")
            f.write("endinterface : axi_lite_if\n\n")

            # AXI4-Stream
            f.write("// --- AXI4-Stream ---\n")
            f.write("interface axi_stream_if #(\n"
                    "  parameter int DW = 32,\n"
                    "  parameter int UW = 1\n"
                    ");\n")
            f.write("  logic [DW-1:0] tdata;\n"
                    "  logic [UW-1:0] tuser;\n"
                    "  logic          tvalid, tready, tlast;\n\n")
            f.write("  modport master (output tdata, tuser, tvalid, tlast, input tready);\n"
                    "  modport slave  (input  tdata, tuser, tvalid, tlast, output tready);\n")
            f.write("endinterface : axi_stream_if\n")

        print(f"  → soc_interfaces.sv")

    # -------------------------------------------------------------------------
    # Generator: soc_top.sv
    # -------------------------------------------------------------------------

    def generate_soc_top(self, output_path):
        ram_size = self.config['soc'].get('ram_size', 32768)
        ext_ports = self._get_external_ports()

        with open(output_path, 'w') as f:
            f.write(AUTOGEN_HEADER)
            f.write(f"// Generated: {ts()}\n")
            f.write("`default_nettype none\n\n")

            # --- Port list ---
            f.write("module soc_top (\n")
            f.write("  input  wire clk_sys,\n")
            f.write("  input  wire rst_ni")

            # Dynamické externé porty z periférií
            for p in ext_ports:
                w = p['width']
                width_str = f" [{w-1}:0]" if w > 1 else "      "
                direction = "output wire" if p['dir'] in ('output',) else \
                            "input  wire" if p['dir'] == 'input' else \
                            "inout  wire"
                port_name = f"{p['periph']}_{p['name']}"
                f.write(f",\n  {direction}{width_str} {port_name}")

            f.write("\n);\n\n")

            # --- Internal signals ---
            f.write("  // --- Bus & IRQ signals ---\n")
            f.write("  bus_if bus();\n")
            f.write("  logic [31:0] irq_lines = '0;\n")
            f.write("  logic        cpu_irq;\n\n")

            # Sel signály pre periférie
            f.write("  // --- Peripheral select signals ---\n")
            f.write("  logic        ram_sel;\n")
            for name, cfg in self.enabled_periphs.items():
                f.write(f"  logic        {name}_sel;\n")
            n = len(self.enabled_periphs)
            f.write(f"  logic [31:0] periph_rdata [0:{n}];\n\n")

            # --- Address decoder ---
            f.write("  // --- Address decoder ---\n")
            f.write("  always_comb begin\n")
            f.write("    ram_sel = (bus.addr < 32'h00010000);\n")
            for name, cfg in self.enabled_periphs.items():
                base = cfg.get('base', 0)
                meta, _ = self.get_ip_meta(name)
                size = meta.get('address_range', 0x10) if meta else 0x10
                if isinstance(size, str):
                    size = int(size, 16)
                f.write(f"    {name}_sel = (bus.addr >= 32'h{base:08X}) && "
                        f"(bus.addr < 32'h{base + size:08X});\n")
            f.write("  end\n\n")

            # --- Read mux ---
            f.write("  // --- Read data mux ---\n")
            f.write("  always_comb begin\n")
            f.write("    bus.rdata = '0;\n")
            f.write("    bus.ready = 1'b0;\n")
            f.write("    if (ram_sel) begin\n")
            f.write("      bus.rdata = periph_rdata[0];\n")
            f.write("      bus.ready = 1'b1;\n")
            f.write("    end\n")
            for idx, name in enumerate(self.enabled_periphs, 1):
                f.write(f"    else if ({name}_sel) begin\n")
                f.write(f"      bus.rdata = periph_rdata[{idx}];\n")
                f.write(f"      bus.ready = 1'b1;\n")
                f.write(f"    end\n")
            f.write("  end\n\n")

            # --- CPU ---
            f.write("  // --- PicoRV32 CPU ---\n")
            f.write("  picorv32 #(\n")
            f.write("    .ENABLE_IRQ(1),\n")
            f.write("    .PROGADDR_RESET(32'h0000_0000)\n")
            f.write("  ) u_cpu (\n")
            f.write("    .clk        (clk_sys),\n")
            f.write("    .resetn     (rst_ni),\n")
            f.write("    .mem_valid  (bus.valid),\n")
            f.write("    .mem_addr   (bus.addr),\n")
            f.write("    .mem_wdata  (bus.wdata),\n")
            f.write("    .mem_wstrb  (bus.be),\n")
            f.write("    .mem_ready  (bus.ready),\n")
            f.write("    .mem_rdata  (bus.rdata),\n")
            f.write("    .irq        ({31'b0, cpu_irq})\n")
            f.write("  );\n\n")

            # --- RAM ---
            f.write("  // --- On-chip RAM ---\n")
            f.write(f"  soc_ram #(\n")
            f.write(f"    .SIZE_BYTES ({ram_size}),\n")
            f.write(f"    .INIT_FILE  (\"software.hex\")\n")
            f.write(f"  ) u_ram (\n")
            f.write(f"    .clk   (clk_sys),\n")
            f.write(f"    .addr  (bus.addr[{ram_size.bit_length()-1}:2]),\n")
            f.write(f"    .be    (bus.be),\n")
            f.write(f"    .we    (|bus.be & ram_sel & bus.valid),\n")
            f.write(f"    .wdata (bus.wdata),\n")
            f.write(f"    .rdata (periph_rdata[0])\n")
            f.write(f"  );\n\n")

            # --- Peripherals ---
            f.write("  // --- Peripherals ---\n")
            for idx, (name, cfg) in enumerate(self.enabled_periphs.items(), 1):
                meta, base_type = self.get_ip_meta(name)
                if not meta:
                    f.write(f"  // WARNING: '{name}' nenájdený v ip_registry — preskočený\n\n")
                    continue

                module = meta.get('module', f"{base_type}_top")
                f.write(f"  {module} u_{name} (\n")
                f.write(f"    .clk_i  (clk_sys),\n")
                f.write(f"    .rst_ni (rst_ni),\n")
                f.write(f"    .addr_i (bus.addr[7:2]),\n")
                f.write(f"    .wdata_i(bus.wdata),\n")
                f.write(f"    .we_i   (|bus.be & {name}_sel & bus.valid),\n")
                f.write(f"    .rdata_o(periph_rdata[{idx}])")

                # Externé signály
                for iface in meta.get('interfaces', []):
                    if iface.get('type') not in ('simple_bus',):
                        for sig in iface.get('signals', []):
                            port_name = f"{name}_{sig['name']}"
                            f.write(f",\n    .{sig['name']}_o ({port_name})"
                                    if sig['dir'] == 'output'
                                    else f",\n    .{sig['name']}_i ({port_name})")

                # IRQ pripojenie
                for irq in meta.get('interrupts', []):
                    irq_id = irq['id']
                    f.write(f",\n    .irq_o  (irq_lines[{irq_id}])")

                f.write(f"\n  );\n\n")

            # --- INTC (ak je aktívny) ---
            if 'intc' in self.enabled_periphs:
                f.write("  // --- Interrupt controller → CPU ---\n")
                f.write("  assign cpu_irq = |irq_lines;\n\n")

            f.write("endmodule : soc_top\n")

        print(f"  → soc_top.sv")

    # -------------------------------------------------------------------------
    # Generator: generated_config.tcl
    # -------------------------------------------------------------------------

    def generate_tcl_config(self, output_path):
        with open(output_path, 'w') as f:
            f.write(AUTOGEN_HEADER_TCL)
            f.write(f"# Generated: {ts()}\n\n")
            f.write("set GENERATED_CONFIG 1\n")

            board_type = self.config.get("board", {}).get("type", "qmtech_ep4ce55")
            f.write(f"set BOARD_TYPE {board_type}\n\n")

            # On-board periférie
            f.write("# --- On-board peripherals ---\n")
            onb = self.config.get("onboard", {})
            for name in ["seg", "dig", "leds", "buttons", "uart", "vga",
                         "sdram", "eth", "sdc", "cam"]:
                val = 1 if onb.get(name, False) else 0
                f.write(f"set ONB_USE_{name.upper()} {val}\n")

            # PMOD
            f.write("\n# --- PMOD configuration ---\n")
            pmod = self.config.get("pmod", {})
            for port, module in pmod.items():
                f.write(f"set PMOD({port}) \"{module}\"\n")

            # Periférie (adresy pre prípadný TCL audit)
            f.write("\n# --- Active peripheral addresses ---\n")
            for name, cfg in self.enabled_periphs.items():
                base = cfg.get('base', 0)
                f.write(f"set PERIPH_BASE({name}) 0x{base:08X}\n")

        print(f"  → generated_config.tcl")

    # -------------------------------------------------------------------------
    # Generator: soc_map.h
    # -------------------------------------------------------------------------

    def generate_soc_map_h(self, output_path):
        with open(output_path, 'w') as f:
            f.write(AUTOGEN_HEADER_C)
            f.write(f"// Generated: {ts()}\n\n")
            f.write("#ifndef SOC_MAP_H\n#define SOC_MAP_H\n\n")
            f.write("#include <stdint.h>\n\n")

            clk = self.config['soc'].get('clock_freq', 50_000_000)
            ram = self.config['soc'].get('ram_size', 32768)
            f.write(f"#define SYS_CLK_HZ     {clk}UL\n")
            f.write(f"#define RAM_SIZE_BYTES {ram}U\n\n")

            for name, cfg in self.enabled_periphs.items():
                base = cfg.get('base', 0)
                guard = name.upper()
                meta, _ = self.get_ip_meta(name)

                f.write(f"/* --- {name} --- */\n")
                f.write(f"#define {guard}_BASE  (0x{base:08X}UL)\n")

                if meta:
                    for reg in meta.get('registers', []):
                        reg_name   = reg['name']
                        reg_offset = reg['offset']
                        if isinstance(reg_offset, str):
                            reg_offset = int(reg_offset, 16)
                        f.write(f"#define {guard}_{reg_name}_REG "
                                f"(*((volatile uint32_t*)({guard}_BASE + 0x{reg_offset:02X}UL)))\n")
                f.write("\n")

            f.write("#endif /* SOC_MAP_H */\n")

        print(f"  → soc_map.h")

    # -------------------------------------------------------------------------
    # Generator: soc_irq.h
    # -------------------------------------------------------------------------

    def generate_soc_irq_h(self, output_path):
        # Zozbieraj všetky IRQ zo všetkých aktívnych periférií
        irq_map = {}
        for name in self.enabled_periphs:
            meta, _ = self.get_ip_meta(name)
            if not meta:
                continue
            for irq in meta.get('interrupts', []):
                irq_id   = irq['id']
                irq_name = f"{name.upper()}_{irq['name'].upper()}_IRQ"
                if irq_id in irq_map:
                    print(f"⚠️  IRQ kolízia: ID {irq_id} použité pre "
                          f"'{irq_map[irq_id]}' aj '{irq_name}'")
                irq_map[irq_id] = irq_name

        with open(output_path, 'w') as f:
            f.write(AUTOGEN_HEADER_C)
            f.write(f"// Generated: {ts()}\n\n")
            f.write("#ifndef SOC_IRQ_H\n#define SOC_IRQ_H\n\n")

            if irq_map:
                for irq_id in sorted(irq_map):
                    f.write(f"#define {irq_map[irq_id]:40s} {irq_id}U\n")
            else:
                f.write("/* No interrupts configured */\n")

            f.write("\n#endif /* SOC_IRQ_H */\n")

        print(f"  → soc_irq.h")

    # -------------------------------------------------------------------------
    # Generator: sections.lds
    # -------------------------------------------------------------------------

    def generate_linker_script(self, output_path):
        ram_size = self.config['soc'].get('ram_size', 32768)
        with open(output_path, 'w') as f:
            f.write(f"/* AUTO-GENERATED BY gen_config.py — DO NOT EDIT MANUALLY */\n")
            f.write(f"/* Generated: {ts()} */\n\n")
            f.write("OUTPUT_ARCH(riscv)\n")
            f.write("ENTRY(_start)\n\n")
            f.write("MEMORY {\n")
            f.write(f"  RAM (rwx) : ORIGIN = 0x00000000, LENGTH = {ram_size}\n")
            f.write("}\n\n")
            f.write("SECTIONS {\n")
            f.write("  .text : {\n"
                    "    *(.text.start)\n"
                    "    *(.text*)\n"
                    "    *(.rodata*)\n"
                    "  } > RAM\n\n")
            f.write("  .data : {\n"
                    "    *(.data*)\n"
                    "  } > RAM\n\n")
            f.write("  .bss : {\n"
                    "    __bss_start = .;\n"
                    "    *(.bss*)\n"
                    "    *(COMMON)\n"
                    "    __bss_end = .;\n"
                    "  } > RAM\n\n")
            f.write("  _stack_top = ORIGIN(RAM) + LENGTH(RAM);\n")
            f.write("}\n")

        print(f"  → sections.lds")

    # -------------------------------------------------------------------------
    # Hlavná metóda
    # -------------------------------------------------------------------------

    def generate_all(self):
        gen_sv_dir  = os.path.join(self.root_dir, "src",  "soc", "gen")
        cfg_dir     = os.path.join(self.root_dir, "board", "config")
        sw_inc_dir  = os.path.join(self.root_dir, "sw",   "include")
        sw_ld_dir   = os.path.join(self.root_dir, "sw",   "linker")

        for d in [gen_sv_dir, cfg_dir, sw_inc_dir, sw_ld_dir]:
            os.makedirs(d, exist_ok=True)

        print(f"\n🚀  Generujem SoC — root: {self.root_dir}")
        print(f"    Aktívne periférie: {list(self.enabled_periphs.keys())}\n")

        self.generate_interfaces(os.path.join(gen_sv_dir, "soc_interfaces.sv"))
        self.generate_soc_top   (os.path.join(gen_sv_dir, "soc_top.sv"))
        self.generate_tcl_config(os.path.join(cfg_dir,    "generated_config.tcl"))
        self.generate_soc_map_h (os.path.join(sw_inc_dir, "soc_map.h"))
        self.generate_soc_irq_h (os.path.join(sw_inc_dir, "soc_irq.h"))
        self.generate_linker_script(os.path.join(sw_ld_dir, "sections.lds"))

        print(f"\n✅  Hotovo — všetky súbory vygenerované.")


# =============================================================================
if __name__ == "__main__":
    builder = SoCBuilder()
    builder.generate_all()

