/* AUTO-GENERATED BY gen_config.py — DO NOT EDIT MANUALLY */
// Generated: 2026-03-22 12:43:26

#ifndef SOC_MAP_H
#define SOC_MAP_H

#include <stdint.h>

#define SYS_CLK_HZ     50000000UL
#define RAM_SIZE_BYTES 4096U

/* --- intc --- */
#define INTC_BASE  (0x80001000UL)
#define INTC_ENABLE_REG (*((volatile uint32_t*)(INTC_BASE + 0x00UL)))
#define INTC_PENDING_REG (*((volatile uint32_t*)(INTC_BASE + 0x04UL)))
#define INTC_CLAIM_REG (*((volatile uint32_t*)(INTC_BASE + 0x08UL)))
#define INTC_COMPLETE_REG (*((volatile uint32_t*)(INTC_BASE + 0x0CUL)))

/* --- seg7_0 --- */
#define SEG7_0_BASE  (0x80004000UL)

/* --- timer0 --- */
#define TIMER0_BASE  (0x80005000UL)

#endif /* SOC_MAP_H */
