/* AUTO-GENERATED BY gen_config.py — DO NOT EDIT MANUALLY */
// Generated: 2026-03-22 12:43:26

#ifndef SOC_IRQ_H
#define SOC_IRQ_H

#define TIMER0_ALARM_IRQ                         2U

#endif /* SOC_IRQ_H */
