# AUTO-GENERATED BY gen_config.py - DO NOT EDIT MANUALLY
# Generated: 2026-03-22 15:26:24

set_global_assignment -name SYSTEMVERILOG_FILE soc_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../../src/soc/static/seg7_counter.sv
